all_atoms: false
atom_max_neighbors: 8
atom_radius: 5
batch_size: 16
best_model_save_frequency: 0
c_alpha_max_neighbors: 24
cache_path: cache
chain_cutoff: 10
ckpt: best_inference_epoch_model.pt
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
data_dir: data/PDBBind_processed
distance_embed_dim: 32
dropout: 0.0
esm_embeddings_path: data/esm2_3billion_embeddings.pt
latent_dropout: 0.0
latent_hidden_dim: 128
latent_no_batchnorm: false
latent_nodes_residual: false
latent_virtual_nodes: false
limit_complexes: 0
log_dir: workdir
lr: 0.001
main_metric: accuracy
main_metric_goal: max
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
model_save_frequency: 0
n_epochs: 1000
no_batch_norm: false
no_randomness: true
no_sampling: true
no_torsion: false
ns: 16
num_accumulation_steps: 1
num_conformers: 1
num_conv_layers: 2
nv: 4
original_model_dir: workdir/disco_diffdockS_score_model
overfit: false
project: diffdock_latent_ar
receptor_radius: 15.0
remove_hs: true
restart_dir: null
run_name: disco_diffdockS_ar_model
sampling_latent_temperature: 0.01
scheduler: plateau
scheduler_patience: 30
sh_lmax: 2
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
train_multiplicity: 1
use_pretrained_score: true
use_second_order_repr: false
val_multiplicity: 1
w_decay: 0.0
wandb: true
warmup_epochs: 5
