all_atoms: false
atom_max_neighbors: 8
atom_radius: 5
batch_size: 16
c_alpha_max_neighbors: 24
cache_path: cache
config: null
cross_attention_dim: 64
cross_attention_heads: 1
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
data_dir: data/PDBBind_processed
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
encoder_cross_max_distance: 30.0
encoder_no_esm: false
encoder_ns: 24
encoder_num_conv_layers: 3
encoder_nv: 4
esm_embeddings_path: data/esm2_3billion_embeddings.pt
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
latent_cross_attention: false
latent_dim: 0
latent_dropout: 0.0
latent_hidden_dim: 128
latent_no_batchnorm: false
latent_nodes_residual: false
latent_virtual_nodes: false
latent_vocab: 64
limit_complexes: 0
log_dir: workdir
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
n_epochs: 1000
new_cross_attention: false
no_batch_norm: false
no_torsion: false
ns: 24
num_conformers: 1
num_conv_layers: 5
num_dataloader_workers: 1
num_inference_complexes: 500
num_workers: 1
nv: 6
pin_memory: false
project: ligbind_train
receptor_radius: 15.0
remove_hs: true
restart_lr: null
rot_sigma_max: 1.55
rot_sigma_min: 0.03
rot_weight: 0.33
run_name: nodiscrete_lmax1
sampling_alpha: 2
sampling_beta: 1
sampling_latent_temperature: 0.01
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
sh_lmax: 1
sigma_embed_dim: 32
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
test_sigma_intervals: true
tor_sigma_max: 3.14
tor_sigma_min: 0.03
tor_weight: 0.33
tr_sigma_max: 19.0
tr_sigma_min: 0.1
tr_weight: 0.33
train_inference_freq: null
train_multiplicity: 1
training_latent_temperature: 1.0
use_ema: true
use_old_atom_encoder: false
use_second_order_repr: false
val_inference_freq: 5
val_multiplicity: 1
w_decay: 0.0
wandb: true
